version: 2

jobs:
  build:
    docker:
      - image: circleci/node:carbon-browsers
    working_directory: /home/circleci/repo
    steps:
      - checkout
      - run: yarn
      - run: node -p "require('bcrypt').hashSync('password', 5)"
